-- AlterTable
ALTER TABLE "Homework" ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "HomeworkSubmission" ALTER COLUMN "grade" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "point" SET DATA TYPE DOUBLE PRECISION;
